# -*- coding: utf-8 -*-
"""PandasDataAnalyse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jXbzHg0lhsbuuU6YAVFJzfVPFiPK_STV
"""

import numpy as np
import pandas as pd

train_df = pd.read_csv("/content/train.csv")

train_df.head()

train_df.tail()

train_df.columns

train_df.describe()

train_df.info()

train_df.isnull().sum()

#Group by Pclass and look how percentage is survived
train_df[["Pclass","Survived"]].groupby(["Pclass"], as_index = False).mean().sort_values(by="Survived",ascending = False)

##Group by Sex and look how percentage is survived
train_df[["Sex","Survived"]].groupby(["Sex"], as_index = False).mean().sort_values(by="Survived",ascending = False)

train_df[["SibSp","Survived"]].groupby(["SibSp"], as_index = False).mean().sort_values(by="Survived",ascending = False)

train_df[["Parch","Survived"]].groupby(["Parch"], as_index = False).mean().sort_values(by="Survived",ascending = False)

#Look for missing values
train_df.columns[train_df.isnull().any()]

train_df.isnull().sum()

train_df[train_df["Age"].isnull()]

train_df[train_df["Cabin"].isnull()]

train_df[train_df["Embarked"].isnull()]

#we can fill the missing values of Embarked, I prefer to choose fill with C
train_df["Embarked"] = train_df["Embarked"].fillna("C")
train_df[train_df["Embarked"].isnull()]

#I want to delete the column called Name, Actually it can be related with survived but its just to make practise
train_df.drop(labels = ["Name"], axis = 1, inplace = True)
train_df.head()

